# GenDB will store collections of various schemas.  Given a prompt, it will automaticaly 
# generate a virtual schema for an LLM such that a query can be generated by the LLM
class GenDBBase
	def __init__(self)
		pass

	# Add a Schema Collection to the Database
	def add_schema(schema):
		print("Add a schema to GenDB")
	
	# Get a Generated Schema view 
	def get_schema(prompt):
		print("This returns a valid SQL schema that is representative of the given prompt")


